enum AppButtonType { primary, secondary, tertiary, outline, text, icon }

enum AppButtonBackgroundColor {
  primary,
  primaryMute,
  primaryThin,
  success,
  successMute,
  successThin,
  warning,
  warningMute,
  warningThin,
  error,
  errorMute,
  errorThin,
  surfacePrimaryBG,
  surfaceLayer,
  surfaceMute,
  surfaceMild,
  extra,
  extraMute,
  extraThin,
  backdropSoft,
  backdropMild,
  backdropWarm,
}

enum AppButtonForegroundColor {
  primary,
  primaryMute,
  primaryThin,
  success,
  successMute,
  successThin,
  warning,
  warningMute,
  warningThin,
  error,
  errorMute,
  errorThin,
  textPrimary,
  textMute,
  textBrand,
  textInverted,
  textDisabled,
  iconPrimary,
  iconMute,
  iconBrand,
  iconInverted,
  iconDisabled,
  oncolorWhite,
  oncolorBlack,
  extra,
  extraMute,
  extraThin,
}

enum AppButtonBorderColor {
  strokeSoft,
  strokeSubtle,
  strokeMild,
  strokeWarm,
  strokeStrong,
  strokePrimary,
  primary,
  primaryMute,
  primaryThin,
  extra,
}
